[package]
name = "good_stv"
version = "0.1.0"
authors = ["Terry Bolt <bolt.terry@gmail.com>"]

[dependencies]
clap = "2.27.1"
csv = "1.0.0-beta.5"
env_logger = "0.4.3"
error-chain = "0.11.0"
log = "0.3.8"
rand = "0.3.18"
serde = "1"
serde_derive = "1"
